import sys
from pathlib import Path

backend_dir = Path(__file__).parent
sys.path.insert(0, str(backend_dir))

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from typing import List
import uvicorn
from dotenv import load_dotenv

from models.schemas import *
from agents.orchestrator import Orchestrator

load_dotenv()

app = FastAPI(title="HydraHacks Quant Validator API")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

@app.get("/")
async def root():
    return {"message": "HydraHacks API - Optimized Version", "status": "running"}

@app.post("/api/generate", response_model=GenerationResponse)
async def generate_problems(request: GenerationRequest):
    """Generate problems with minimal API calls"""
    
    try:
        orchestrator = Orchestrator()
        result = orchestrator.generate_problems(
            num_problems=request.num_problems,
            category=request.category.value
        )
        
        return GenerationResponse(**result)
    
    except Exception as e:
        print(f"Error: {e}")
        import traceback
        traceback.print_exc()
        raise HTTPException(status_code=500, detail=str(e))

@app.post("/api/export/html")
async def export_html(problems: List[Problem]):
    """Generate HTML quiz"""
    
    html = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Quantitative Aptitude Quiz - HydraHacks</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { 
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            padding: 40px 20px;
        }
        .container {
            max-width: 900px;
            margin: 0 auto;
            background: white;
            border-radius: 20px;
            padding: 40px;
            box-shadow: 0 20px 60px rgba(0,0,0,0.3);
        }
        h1 { 
            color: #667eea;
            font-size: 2.5rem;
            margin-bottom: 10px;
            text-align: center;
        }
        .subtitle {
            text-align: center;
            color: #666;
            margin-bottom: 40px;
            font-size: 1.1rem;
        }
        .problem {
            margin: 40px 0;
            padding: 30px;
            background: #f8f9fa;
            border-radius: 15px;
            border-left: 5px solid #667eea;
        }
        .problem-header {
            display: flex;
            justify-content: space-between;
            margin-bottom: 20px;
            padding-bottom: 15px;
            border-bottom: 2px solid #e0e0e0;
        }
        .problem-id {
            font-weight: 700;
            color: #667eea;
            font-size: 1.3rem;
        }
        .category {
            background: #667eea;
            color: white;
            padding: 5px 15px;
            border-radius: 20px;
            font-size: 0.9rem;
        }
        .question {
            font-size: 1.15rem;
            line-height: 1.8;
            color: #333;
            margin-bottom: 25px;
        }
        .options {
            display: grid;
            gap: 15px;
        }
        .option {
            padding: 15px 20px;
            background: white;
            border: 2px solid #e0e0e0;
            border-radius: 10px;
            transition: all 0.3s;
            cursor: pointer;
        }
        .option:hover {
            border-color: #667eea;
            transform: translateX(5px);
        }
        .option.correct {
            background: #d4edda;
            border-color: #28a745;
            font-weight: 600;
        }
        .explanation {
            margin-top: 20px;
            padding: 15px;
            background: #fff3cd;
            border-radius: 10px;
            border-left: 4px solid #ffc107;
        }
        .explanation strong {
            color: #856404;
        }
        footer {
            text-align: center;
            margin-top: 60px;
            padding-top: 30px;
            border-top: 2px solid #e0e0e0;
            color: #666;
        }
        .stats {
            display: flex;
            justify-content: space-around;
            margin: 30px 0;
            padding: 20px;
            background: #f0f0f0;
            border-radius: 10px;
        }
        .stat {
            text-align: center;
        }
        .stat-value {
            font-size: 2rem;
            font-weight: 700;
            color: #667eea;
        }
        .stat-label {
            color: #666;
            font-size: 0.9rem;
            text-transform: uppercase;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>🎓 Quantitative Aptitude Quiz</h1>
        <p class="subtitle">Generated by HydraHacks Multi-Agent System</p>
        
        <div class="stats">
            <div class="stat">
                <div class="stat-value">""" + str(len(problems)) + """</div>
                <div class="stat-label">Total Questions</div>
            </div>
            <div class="stat">
                <div class="stat-value">""" + str(len(set(p.category for p in problems))) + """</div>
                <div class="stat-label">Categories</div>
            </div>
        </div>
"""
    
    for idx, problem in enumerate(problems, 1):
        html += f"""
        <div class="problem">
            <div class="problem-header">
                <div class="problem-id">{problem.id}</div>
                <div class="category">{problem.category}</div>
            </div>
            
            <div class="question">{problem.question}</div>
            
            <div class="options">
                <div class="option {'correct' if 'A' == problem.correct_answer else ''}">
                    <strong>A)</strong> {problem.options.A}
                </div>
                <div class="option {'correct' if 'B' == problem.correct_answer else ''}">
                    <strong>B)</strong> {problem.options.B}
                </div>
                <div class="option {'correct' if 'C' == problem.correct_answer else ''}">
                    <strong>C)</strong> {problem.options.C}
                </div>
                <div class="option {'correct' if 'D' == problem.correct_answer else ''}">
                    <strong>D)</strong> {problem.options.D}
                </div>
            </div>
            
            <div class="explanation">
                <strong>✓ Correct Answer:</strong> {problem.correct_answer}<br>
                <strong>Explanation:</strong> {problem.explanation[:200]}...
            </div>
        </div>
"""
    
    html += """
        <footer>
            <p><strong>Generated by HydraHacks Multi-Agent Validation System</strong></p>
            <p>Dual-validated with Independent Solver + Ground Truth Verification</p>
        </footer>
    </div>
</body>
</html>"""
    
    return {"html": html}

if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=8000, log_level="info")
